 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reservationcs", type: :request do
  # Reservationc. As you add validations to Reservationc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Reservationc.create! valid_attributes
      get reservationcs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reservationc = Reservationc.create! valid_attributes
      get reservationc_url(reservationc)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reservationc_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      reservationc = Reservationc.create! valid_attributes
      get edit_reservationc_url(reservationc)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Reservationc" do
        expect {
          post reservationcs_url, params: { reservationc: valid_attributes }
        }.to change(Reservationc, :count).by(1)
      end

      it "redirects to the created reservationc" do
        post reservationcs_url, params: { reservationc: valid_attributes }
        expect(response).to redirect_to(reservationc_url(Reservationc.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Reservationc" do
        expect {
          post reservationcs_url, params: { reservationc: invalid_attributes }
        }.to change(Reservationc, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reservationcs_url, params: { reservationc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reservationc" do
        reservationc = Reservationc.create! valid_attributes
        patch reservationc_url(reservationc), params: { reservationc: new_attributes }
        reservationc.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reservationc" do
        reservationc = Reservationc.create! valid_attributes
        patch reservationc_url(reservationc), params: { reservationc: new_attributes }
        reservationc.reload
        expect(response).to redirect_to(reservationc_url(reservationc))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reservationc = Reservationc.create! valid_attributes
        patch reservationc_url(reservationc), params: { reservationc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reservationc" do
      reservationc = Reservationc.create! valid_attributes
      expect {
        delete reservationc_url(reservationc)
      }.to change(Reservationc, :count).by(-1)
    end

    it "redirects to the reservationcs list" do
      reservationc = Reservationc.create! valid_attributes
      delete reservationc_url(reservationc)
      expect(response).to redirect_to(reservationcs_url)
    end
  end
end
